name: issue tracker
on:
  issues:
    types:
      - opened
  workflow_call:

jobs:
  issue-tracker:
    if: ${{ github.event.issue == null || startsWith(github.event.issue.body, '<!-- ISSUE TRACKER ENABLE -->') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Install Aya
        uses: 'aya-prover/aya-dev/.github/actions/install-aya@main'
      - name: Run Issue Tracker
        uses: 'HoshinoTented/issue-tracker@v1'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue: ${{ github.event.issue.number }}
