name: issue tracker
on:
  push:
    branches:
      - main
  issues:
    types:
      - opened

jobs:
  issue-tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Setup Aya
        uses: 'HoshinoTented/setup-aya@v1'
        with:
          # Also, we can reuse previously build aya
          refs: 'main'
      - name: Run Issue Tracker
        uses: 'HoshinoTented/issue-tracker@v1'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue: ${{ github.event.issue.number }}
